version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "the-fair-seat-purchase"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
s3_prefix = "the-fair-seat-purchase"
region = "us-east-1"
disable_rollback = true
